# Assignment: Naive Bayes
## Team: 3musketeers
### Student Names:

- Anu Sebastian - 012496276
- Ravali Nagabandi - 011530454
- Saloni Sharad Bhalerao - 012466623

### Github: https://github.com/anuksebastian/3musketeers

### Team Contribution:
- Data pre-processing - Anu, Ravali
- Training the model - Ravali, Saloni
- Evaluating the model - Saloni, Anu

### Business Objective:
To analyze the dataset for forest fires and to predict occurence of forest fires specific to month attribute by applying Naive Bayes.

In [1]:
import pandas as pd

# load dataset into Pandas DataFrame
dataset = pd.read_csv('/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/Session 4/Assignment 4/Submission/forestfires_0918.csv')

In [2]:
dataset.describe()

X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663   
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477   
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000   
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000   
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000   
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000   
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000   

             temp          RH        wind        rain         area    category  
count  517.000000  517.000000  517.000000  517.000000   517.000000  517.000000  
mean    18.889168   44.288201    4.017602    0.021663    12.847292    1.272727  
std      5.806625   16.317469    1.791653    0.295959    63.655818    0.626522  
min      2.200000   15.000000    0.400000    0.000000     0.000000    1.000000  
25%     15.500000   33.000000    2.700000    0.000000     0.000000    1.000000  
50%     19.300000   42.000000    4.000000    0.000000     0.520000    1.000000  
75%     22.800000   53.000000    4.900000    0.000000     6.570000    1.000000  
max     33.300000  100.000000    9.400000    6.400000  1090.840000    5.000000

### Data preperation: 
#### Download ntlk to tokenize 'month' values:

In [3]:
import nltk  
#nltk.download()  

In [4]:
dataset['month'] = dataset['month'].apply(nltk.word_tokenize)  


In [5]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

dataset['month'] = dataset['month'].apply(lambda x: [stemmer.stem(y) for y in x])  

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

# This converts the list of words into space-separated strings if there are any
dataset['month'] = dataset['month'].apply(lambda x: ' '.join(x))

count_vect = CountVectorizer()  
counts = count_vect.fit_transform(dataset['month'])  

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer().fit(counts)

counts = transformer.transform(counts)  

### Training the model:

In [8]:
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test = train_test_split(counts, dataset['month'], test_size=0.2, random_state=0) 

In [9]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train.toarray(), Y_train)

GaussianNB(priors=None)

### Evaluate the model:

In [10]:
import numpy as np

predicted = clf.predict(X_test.toarray())

print(np.mean(predicted == Y_test))  

1.0


In [11]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test, predicted))  

[[ 1  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0 40]]
