# Assignment 5: Decision Tree
## Team: 3musketeers
### Student Names:

- Anu Sebastian - 012496276
- Ravali Nagabandi - 011530454
- Saloni Sharad Bhalerao - 012466623

### Github: https://github.com/anuksebastian/3musketeers

### Team Contribution:

- Decision tree Classifier - Anu
- Decision tree for Regressor - Ravali
- Decision tree Classifier using python functions - Saloni

### Business Objective:
To analyze the dataset for forest fires and to predict forest fires based on input values provided by the dataset by using Decision Trees.

- In this assignment, we are making use of Decision tree Classifier as well as Decision tree Regressor to classify categorical value. 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from IPython.display import Image

%matplotlib inline

In [2]:
df = pd.read_csv('/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/Foresr Fires/forestfires_0918.csv')

In [3]:
months_table = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 
                'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
days_table =   ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']

df['month'] = [months_table.index(month) for month in df['month'] ]
df['day'] =   [days_table.index(day)     for day   in df['day']   ]

df['X'] -= 1
df['Y'] -= 2

df.head()

X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  \
0  6  3      2    5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0   
1  6  2      9    2  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0   
2  6  2      9    6  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0   
3  7  4      2    5  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0   
4  7  4      2    0  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0   

   category  
0         0  
1         0  
2         0  
3         0  
4         0

In [4]:
df.head(3)

X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  \
0  6  3      2    5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0   
1  6  2      9    2  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0   
2  6  2      9    6  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0   

   category  
0         0  
1         0  
2         0

In [5]:
df.dtypes

X             int64
Y             int64
month         int64
day           int64
FFMC        float64
DMC         float64
DC          float64
ISI         float64
temp        float64
RH            int64
wind        float64
rain        float64
area        float64
category      int64
dtype: object

In [55]:
features = df.drop(['area','category'], axis=1)
target = df.loc[:, ['category']]

In [56]:
# test_size: what proportion of original data is used for test set
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=1)


In [57]:
print(X_train.shape)


(387, 12)


In [58]:
print(y_train.shape)


(387, 1)


In [59]:
print(X_test.shape)


(130, 12)


In [60]:
print(y_test.shape)


(130, 1)


### Classifier:

In [61]:
from sklearn.tree import tree

In [62]:
classifier = tree.DecisionTreeClassifier()
classifier

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [63]:
classifier.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [64]:
y_pred = classifier.predict(X_test)

In [65]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)


0.7

In [66]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[88 13  9  0]
 [ 4  2  1  0]
 [ 9  2  1  0]
 [ 1  0  0  0]]
             precision    recall  f1-score   support

          0       0.86      0.80      0.83       110
          1       0.12      0.29      0.17         7
          2       0.09      0.08      0.09        12
          3       0.00      0.00      0.00         1

avg / total       0.74      0.70      0.72       130



/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [70]:
y_test.head(10)

category
270         0
90          0
133         0
221         2
224         2
286         0
159         0
47          0
298         0
406         0

In [71]:
y_pred

array([0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [72]:
from sklearn import tree

tree.export_graphviz(classifier,out_file='/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/Foresr Fires/classifiertree.dot',feature_names=features.columns)
from subprocess import call
call(['dot', '-T', 'png', '/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/Foresr Fires/classifiertree.dot', '-o', 'classifiertree.png'])

0

### Regressor:

In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from IPython.display import Image

%matplotlib inline

In [74]:
df = pd.read_csv('/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/Foresr Fires/forestfires_0918.csv')

In [75]:
months_table = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 
                'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
days_table =   ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']

df['month'] = [months_table.index(month) for month in df['month'] ]
df['day'] =   [days_table.index(day)     for day   in df['day']   ]

df['X'] -= 1
df['Y'] -= 2

df.head()

X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  \
0  6  3      2    5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0   
1  6  2      9    2  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0   
2  6  2      9    6  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0   
3  7  4      2    5  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0   
4  7  4      2    0  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0   

   category  
0         0  
1         0  
2         0  
3         0  
4         0

In [76]:
df.head(3)

X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  \
0  6  3      2    5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0   
1  6  2      9    2  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0   
2  6  2      9    6  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0   

   category  
0         0  
1         0  
2         0

In [77]:
df.dtypes


X             int64
Y             int64
month         int64
day           int64
FFMC        float64
DMC         float64
DC          float64
ISI         float64
temp        float64
RH            int64
wind        float64
rain        float64
area        float64
category      int64
dtype: object

In [78]:
features = df.loc[:, df.columns != 'category, area']
target = df.loc[:, ['category']]

In [79]:
# test_size: what proportion of original data is used for test set
X_traindata, X_testdata, y_traindata, y_testdata = train_test_split(features, target, random_state=1)

In [80]:
print(X_traindata.shape)


(387, 14)


In [81]:
print(y_traindata.shape)


(387, 1)


In [82]:
print(X_testdata.shape)


(130, 14)


In [83]:
print(y_testdata.shape)


(130, 1)


In [84]:
from sklearn.tree import DecisionTreeRegressor


In [85]:
regr = DecisionTreeRegressor(max_depth = 3)
regr

DecisionTreeRegressor(criterion='mse', max_depth=3, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [86]:
regr.fit(X_traindata, y_traindata)


DecisionTreeRegressor(criterion='mse', max_depth=3, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [87]:
y_predict = regr.predict(X_testdata)

In [88]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_testdata, y_predict))  
print(classification_report(y_testdata, y_predict)) 

[[110   0   0   0]
 [  0   7   0   0]
 [  0   0  12   0]
 [  0   0   1   0]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       110
          1       1.00      1.00      1.00         7
          2       0.92      1.00      0.96        12
          3       0.00      0.00      0.00         1

avg / total       0.99      0.99      0.99       130



/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [89]:
y_testdata

category
270         0
90          0
133         0
221         2
224         2
286         0
159         0
47          0
298         0
406         0
437         0
31          0
283         0
267         0
326         0
334         0
342         0
351         0
512         0
475         0
370         1
102         0
350         0
429         0
318         0
85          0
34          0
408         0
107         0
223         2
..        ...
11          0
358         0
92          0
362         0
135         0
218         2
119         0
463         0
42          0
58          0
394         0
78          0
325         0
164         0
360         0
101         0
142         0
509         0
481         0
439         0
331         1
335         0
473         2
245         0
347         0
18          0
40          0
273         0
503         0
500         0

[130 rows x 1 columns]

In [90]:
y_predict

array([0., 0., 0., 2., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0.,
       2., 0., 0., 0., 0., 0., 1., 0., 2., 0., 0., 0., 2., 0., 1., 0., 0.,
       2., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       2., 0., 2., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 2., 0., 0.,
       0., 0., 0., 0., 2., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 2., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
from sklearn import tree

tree.export_graphviz(regr,out_file='/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/Foresr Fires/regressortree.dot',feature_names=features.columns.values)
from subprocess import call
call(['dot', '-T', 'png', '/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/Foresr Fires/regressortree.dot', '-o', 'regressortree.png'])

0

### Future work:
- Using Decision tree, we understood that month is one of the important factors in predicting fire. In all the previous algorithms, it was observed that temp is the important factor that predicts the occurence of forest fire. We will be investigating on these lines further for this project.